name: usmbro
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^5.0.0
  uuid: ^3.0.7
  shared_preferences: ^2.2.2
  web_socket_channel: ^2.4.0
  flutter_osm_plugin: ^0.60.5
  socket_io_client: ^2.0.3+1
  geolocator: ^10.1.0
  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
